import { app } from 'electron'
import * as fs from 'fs'
import * as path from 'path'

// ─── ID safety ─────────────────────────────────────────────────────────────

const SAFE_ID_RE = /^[A-Za-z0-9_-]+$/

/**
 * Returns true only if the id contains no path separators or traversal sequences.
 * Accepts the alphanumeric+hyphen+underscore ids generated by the app (Math.random hex,
 * Date.now base-36, UUID hex + hyphens, cp_N_M checkpoint ids).
 */
function isSafeId(id: string): boolean {
  return typeof id === 'string' && id.length > 0 && id.length <= 128 && SAFE_ID_RE.test(id)
}

export interface CheckpointFile {
  path: string
  content: string
  existed: boolean
}

export interface Checkpoint {
  id: string
  sessionId: string
  label: string
  createdAt: number
  messageCount: number
  files: CheckpointFile[]
}

export interface CheckpointMeta {
  id: string
  sessionId: string
  label: string
  createdAt: number
  messageCount: number
  fileCount: number
}

const root = path.join(app.getPath('userData'), 'checkpoints')

function sessionDir(sessionId: string): string {
  // isSafeId must be verified before calling sessionDir
  const dir = path.join(root, sessionId)
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true })
  return dir
}

let seq = 0
function genId(): string {
  seq += 1
  return `cp_${seq}_${(seq * 99991) % 1000000}`
}

function snapshotFiles(files: string[]): CheckpointFile[] {
  const seen = new Set<string>()
  const out: CheckpointFile[] = []
  for (const p of files) {
    if (seen.has(p)) continue
    seen.add(p)
    try {
      if (fs.existsSync(p) && fs.statSync(p).isFile()) {
        out.push({ path: p, content: fs.readFileSync(p, 'utf-8'), existed: true })
      } else {
        out.push({ path: p, content: '', existed: false })
      }
    } catch {
      // unreadable — record as non-existing so restore is a no-op
      out.push({ path: p, content: '', existed: false })
    }
  }
  return out
}

function toMeta(c: Checkpoint): CheckpointMeta {
  return {
    id: c.id,
    sessionId: c.sessionId,
    label: c.label,
    createdAt: c.createdAt,
    messageCount: c.messageCount,
    fileCount: c.files.length
  }
}

export function createCheckpoint(
  sessionId: string,
  label: string,
  files: string[],
  messageCount: number,
  createdAt: number
): CheckpointMeta {
  if (!isSafeId(sessionId)) {
    // Return a safe no-op stub; callers that check the id will see a dummy value
    return { id: '', sessionId, label, createdAt, messageCount, fileCount: 0 }
  }
  const cp: Checkpoint = {
    id: genId(),
    sessionId,
    label,
    createdAt,
    messageCount,
    files: snapshotFiles(files)
  }
  fs.writeFileSync(path.join(sessionDir(sessionId), `${cp.id}.json`), JSON.stringify(cp))
  return toMeta(cp)
}

export function listCheckpoints(sessionId: string): CheckpointMeta[] {
  if (!isSafeId(sessionId)) return []
  const dir = path.join(root, sessionId)
  if (!fs.existsSync(dir)) return []
  const metas: CheckpointMeta[] = []
  for (const f of fs.readdirSync(dir).filter((x) => x.endsWith('.json'))) {
    try {
      const c: Checkpoint = JSON.parse(fs.readFileSync(path.join(dir, f), 'utf-8'))
      metas.push(toMeta(c))
    } catch {
      // skip
    }
  }
  return metas.sort((a, b) => b.createdAt - a.createdAt)
}

function read(sessionId: string, id: string): Checkpoint | null {
  if (!isSafeId(sessionId) || !isSafeId(id)) return null
  const p = path.join(root, sessionId, `${id}.json`)
  if (!fs.existsSync(p)) return null
  try {
    return JSON.parse(fs.readFileSync(p, 'utf-8'))
  } catch {
    return null
  }
}

export interface RestoreResult {
  restored: number
  safetyCheckpointId: string | null
}

export function restoreCheckpoint(sessionId: string, id: string, createdAt: number): RestoreResult {
  if (!isSafeId(sessionId) || !isSafeId(id)) return { restored: 0, safetyCheckpointId: null }
  const cp = read(sessionId, id)
  if (!cp) return { restored: 0, safetyCheckpointId: null }

  // Safety net: snapshot the CURRENT state of these files before overwriting, so the
  // restore itself can be undone.
  const safety = createCheckpoint(
    sessionId,
    `Before restore of "${cp.label}"`,
    cp.files.map((f) => f.path),
    cp.messageCount,
    createdAt
  )

  let restored = 0
  for (const f of cp.files) {
    try {
      if (f.existed) {
        fs.mkdirSync(path.dirname(f.path), { recursive: true })
        fs.writeFileSync(f.path, f.content)
        restored++
      } else if (fs.existsSync(f.path)) {
        fs.unlinkSync(f.path)
        restored++
      }
    } catch {
      // skip files we can't write
    }
  }
  return { restored, safetyCheckpointId: safety.id }
}

export function deleteCheckpoint(sessionId: string, id: string): CheckpointMeta[] {
  if (!isSafeId(sessionId) || !isSafeId(id)) return listCheckpoints(sessionId)
  const p = path.join(root, sessionId, `${id}.json`)
  if (fs.existsSync(p)) fs.unlinkSync(p)
  return listCheckpoints(sessionId)
}

export interface CheckpointFileDiff {
  path: string
  before: string
  after: string
}

export interface CheckpointDiff {
  files: CheckpointFileDiff[]
}

/**
 * Compare two checkpoints (or one checkpoint vs current on-disk state).
 * Pass idB = 'current' to compare the snapshot against what's on disk right now.
 */
// Files larger than this are skipped from diffing to avoid freezing the UI.
const MAX_FILE_BYTES = 512 * 1024 // 512 KB

/** Returns true if the content looks like binary (contains a null byte in the first 8 KB). */
function looksLikeBinary(content: string): boolean {
  return content.slice(0, 8192).includes('\x00')
}

/** Safely read a file from disk, returning '' on any error or if the file is too large / binary. */
function safeReadFile(filePath: string): string {
  try {
    if (!fs.existsSync(filePath) || !fs.statSync(filePath).isFile()) return ''
    const stat = fs.statSync(filePath)
    if (stat.size > MAX_FILE_BYTES) return ''
    const content = fs.readFileSync(filePath, 'utf-8')
    if (looksLikeBinary(content)) return ''
    return content
  } catch {
    return ''
  }
}

/** Cap a snapshot content string: treat it as '' if too large or binary. */
function safeSnapshotContent(content: string): string {
  if (content.length > MAX_FILE_BYTES) return ''
  if (looksLikeBinary(content)) return ''
  return content
}

export function compareCheckpoints(
  sessionId: string,
  idA: string,
  idB: string
): CheckpointDiff {
  if (!isSafeId(sessionId) || !isSafeId(idA) || (idB !== 'current' && !isSafeId(idB))) return { files: [] }
  const cpA = read(sessionId, idA)
  if (!cpA) return { files: [] }

  const allPaths = new Set<string>(cpA.files.map((f) => f.path))

  let bMap: Map<string, string>
  if (idB === 'current') {
    // Read current on-disk content for each path in cpA
    bMap = new Map()
    for (const f of cpA.files) {
      bMap.set(f.path, safeReadFile(f.path))
    }
  } else {
    const cpB = read(sessionId, idB)
    if (!cpB) return { files: [] }
    for (const f of cpB.files) allPaths.add(f.path)
    bMap = new Map(cpB.files.map((f) => [f.path, f.existed ? safeSnapshotContent(f.content) : '']))
  }

  const aMap = new Map(cpA.files.map((f) => [f.path, f.existed ? safeSnapshotContent(f.content) : '']))

  const files: CheckpointFileDiff[] = []
  for (const p of allPaths) {
    const before = aMap.get(p) ?? ''
    const after = bMap.get(p) ?? ''
    if (before !== after) {
      files.push({ path: p, before, after })
    }
  }
  return { files }
}

// ─── Minimal LCS-based unified diff ──────────────────────────────────────────

/**
 * Maximum allowed product of line counts for LCS computation.
 * 5 000 000 ≈ ~200 MB of number[][] at 8 bytes/number — stays well within Node's heap.
 * Files that exceed this produce a placeholder diff entry instead of crashing.
 */
const LCS_MAX_CELLS = 5_000_000

function lcs(a: string[], b: string[]): number[][] {
  const n = a.length
  const m = b.length
  const dp: number[][] = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(0))
  for (let i = n - 1; i >= 0; i--) {
    for (let j = m - 1; j >= 0; j--) {
      dp[i][j] = a[i] === b[j] ? dp[i + 1][j + 1] + 1 : Math.max(dp[i + 1][j], dp[i][j + 1])
    }
  }
  return dp
}

type EditOp = { type: 'context' | 'add' | 'del'; text: string }

function buildEdits(a: string[], b: string[], dp: number[][]): EditOp[] {
  const ops: EditOp[] = []
  let i = 0
  let j = 0
  while (i < a.length && j < b.length) {
    if (a[i] === b[j]) {
      ops.push({ type: 'context', text: a[i] })
      i++
      j++
    } else if (dp[i + 1][j] >= dp[i][j + 1]) {
      ops.push({ type: 'del', text: a[i] })
      i++
    } else {
      ops.push({ type: 'add', text: b[j] })
      j++
    }
  }
  while (i < a.length) ops.push({ type: 'del', text: a[i++] })
  while (j < b.length) ops.push({ type: 'add', text: b[j++] })
  return ops
}

function buildUnifiedPatch(filePath: string, before: string, after: string, context = 3): string {
  // Detect whether each side ends with a newline.
  const aNoNewline = before.length > 0 && !before.endsWith('\n')
  const bNoNewline = after.length > 0 && !after.endsWith('\n')

  // Split into lines. An empty string means the file doesn't exist / is empty → 0 lines.
  const aLines = before === '' ? [] : before.split('\n')
  const bLines = after === '' ? [] : after.split('\n')

  // Identical files (empty vs empty, or same content) — no patch needed.
  if (before === after) return ''

  // Guard against OOM: if the LCS matrix would exceed LCS_MAX_CELLS cells, skip diff.
  if (aLines.length * bLines.length > LCS_MAX_CELLS) {
    const safeFile = filePath.replace(/\\/g, '/')
    return `--- a/${safeFile}\n+++ b/${safeFile}\n@@ diff too large to display (${aLines.length} × ${bLines.length} lines) @@\n`
  }

  const dp = lcs(aLines, bLines)
  const ops = buildEdits(aLines, bLines, dp)

  // Map ops back to 1-based line numbers.
  type TaggedOp = EditOp & { aLine: number; bLine: number }
  const tagged: TaggedOp[] = []
  let aLine = 1
  let bLine = 1
  for (const op of ops) {
    tagged.push({ ...op, aLine, bLine })
    if (op.type !== 'add') aLine++
    if (op.type !== 'del') bLine++
  }

  // Find change positions and group into hunks.
  const changeIdx = tagged
    .map((op, i) => (op.type !== 'context' ? i : -1))
    .filter((i) => i >= 0)

  if (changeIdx.length === 0) return ''

  const hunks: Array<{ start: number; end: number }> = []
  let hStart = Math.max(0, changeIdx[0] - context)
  let hEnd = Math.min(tagged.length - 1, changeIdx[0] + context)
  for (let k = 1; k < changeIdx.length; k++) {
    const idx = changeIdx[k]
    if (idx - context <= hEnd + 1) {
      hEnd = Math.min(tagged.length - 1, idx + context)
    } else {
      hunks.push({ start: hStart, end: hEnd })
      hStart = Math.max(0, idx - context)
      hEnd = Math.min(tagged.length - 1, idx + context)
    }
  }
  hunks.push({ start: hStart, end: hEnd })

  const safeFile = filePath.replace(/\\/g, '/')
  // Pure-add: no "before" side → use /dev/null as the source.
  // Pure-delete: no "after" side → use /dev/null as the destination.
  const aHeader = before === '' ? '--- /dev/null' : `--- a/${safeFile}`
  const bHeader = after === '' ? '+++ /dev/null' : `+++ b/${safeFile}`
  const header = `${aHeader}\n${bHeader}\n`

  const isLastHunk = (idx: number) => idx === hunks.length - 1

  const hunkTexts = hunks.map((h, hIdx) => {
    const slice = tagged.slice(h.start, h.end + 1)
    const aCount = slice.filter((o) => o.type !== 'add').length
    const bCount = slice.filter((o) => o.type !== 'del').length

    // For pure-add files, aLine of the first op is 1 but the convention is "0" for the
    // old-side start when aCount === 0 (no lines from the old file).
    const rawAStart = slice[0].aLine
    const rawBStart = slice[0].bLine
    const aStart = aCount === 0 ? 0 : rawAStart
    const bStart = bCount === 0 ? 0 : rawBStart

    // Standard unified diff omits the ",count" when count === 1, but git diff always
    // includes it. We always include it for compatibility with `patch`.
    const hunkHeader = `@@ -${aStart},${aCount} +${bStart},${bCount} @@`

    const lines: string[] = []
    for (let oi = 0; oi < slice.length; oi++) {
      const o = slice[oi]
      const sign = o.type === 'add' ? '+' : o.type === 'del' ? '-' : ' '
      lines.push(`${sign}${o.text}`)
      // Append "\ No newline at end of file" when this is the very last line of the
      // last hunk and the corresponding side lacked a trailing newline.
      if (isLastHunk(hIdx) && oi === slice.length - 1) {
        const isLastA = o.type !== 'add' && aNoNewline
        const isLastB = o.type !== 'del' && bNoNewline
        if (isLastA || isLastB) {
          lines.push('\\ No newline at end of file')
        }
      }
    }

    return [hunkHeader, ...lines].join('\n')
  })

  return header + hunkTexts.join('\n') + '\n'
}

/**
 * Build a unified-diff patch comparing a checkpoint's snapshot against
 * current on-disk state, or against another checkpoint (idB = 'current' for disk).
 */
export function exportPatch(sessionId: string, idA: string, idB: string): string {
  if (!isSafeId(sessionId) || !isSafeId(idA) || (idB !== 'current' && !isSafeId(idB))) return ''
  const diff = compareCheckpoints(sessionId, idA, idB)
  if (diff.files.length === 0) return ''
  return diff.files.map((f) => buildUnifiedPatch(f.path, f.before, f.after)).join('\n')
}
