import { app } from 'electron'
import * as fs from 'fs'
import * as path from 'path'
import { readJsonFile } from './json-file'

// A sprint is a multi-week Scrum artifact, stored as one JSON file per sprint keyed
// by its id in userData/sprints (mirroring the agents.ts / planner.ts pattern). Unlike
// WeekPlan (Monday-keyed), a sprint spans an arbitrary date range, so it gets its own
// store rather than being embedded in the week planner.

export type SprintStatus = 'planning' | 'active' | 'completed'
export type ItemStatus = 'todo' | 'in-progress' | 'done'

export interface SprintItem {
  id: string
  title: string
  notes?: string | null
  status: ItemStatus
  /** Story points. null/undefined = unestimated (counts as 0 in burndown). */
  points?: number | null
  createdAt: number
  /** Set the moment the item first enters 'done' — the burndown x-axis anchor. */
  completedAt?: number | null
  /** The status this item held before its current one — lets un-checking 'done' restore it. */
  prevStatus?: ItemStatus | null
}

/** Cached GitLab backfill so re-opening the importer doesn't re-hit the MCP each time. */
export interface SprintBackfillCache {
  fetchedAt: number
  project?: string
  projectUrl?: string
  source?: string
  note?: string
  openIssueCount?: number | null
  items: { title: string; points?: number | null; notes?: string }[]
}

export interface DailyStandup {
  /** ISO date "YYYY-MM-DD" — the key; one standup per date per sprint. */
  date: string
  yesterday: string
  today: string
  blockers: string
  updatedAt: number
}

export interface Sprint {
  /** Stable id, doubles as the storage key. */
  id: string
  name: string
  goal?: string
  /** ISO date "YYYY-MM-DD". */
  startDate: string
  /** ISO date "YYYY-MM-DD", inclusive. */
  endDate: string
  status: SprintStatus
  items: SprintItem[]
  standups: DailyStandup[]
  /** Project folder standups/metrics default to (for git-log digest). */
  projectPath?: string
  /** Last GitLab backfill result, cached so the importer opens instantly. */
  backfillCache?: SprintBackfillCache
  createdAt: number
  updatedAt: number
}

const sprintsDir = path.join(app.getPath('userData'), 'sprints')

function ensureSprintsDir(): void {
  if (!fs.existsSync(sprintsDir)) fs.mkdirSync(sprintsDir, { recursive: true })
}

function fileFor(id: string): string {
  // id is generated by the renderer (uuid/random), but sanitize for a safe filename.
  const safe = id.replace(/[^a-zA-Z0-9_-]/g, '')
  return path.join(sprintsDir, `${safe}.json`)
}

/** Backfill optional fields so older saved sprints stay valid as the shape grows. */
function normalize(s: Sprint): Sprint {
  return {
    status: 'active',
    items: [],
    standups: [],
    ...s,
    items: Array.isArray(s.items) ? s.items : [],
    standups: Array.isArray(s.standups) ? s.standups : []
  }
}

/** All sprints, most recently updated first. */
export function listSprints(): Sprint[] {
  ensureSprintsDir()
  try {
    return fs
      .readdirSync(sprintsDir)
      .filter((f) => f.endsWith('.json'))
      .map((f) => normalize(readJsonFile<Sprint>(path.join(sprintsDir, f))))
      .sort((a, b) => b.updatedAt - a.updatedAt)
  } catch {
    return []
  }
}

export function getSprint(id: string): Sprint | null {
  const p = fileFor(id)
  if (!fs.existsSync(p)) return null
  try {
    return normalize(readJsonFile<Sprint>(p))
  } catch {
    return null
  }
}

export function saveSprint(sprint: Sprint): Sprint {
  ensureSprintsDir()
  const next: Sprint = { ...normalize(sprint), updatedAt: Date.now() }
  fs.writeFileSync(fileFor(sprint.id), JSON.stringify(next, null, 2))
  return next
}

export function deleteSprint(id: string): Sprint[] {
  const p = fileFor(id)
  if (fs.existsSync(p)) fs.unlinkSync(p)
  return listSprints()
}
